rubber:
  proxy:
    dbSetName: USER_DB_CLUSTER
    db:
      USER_DB_SINGLE:
        setDbName: USER_DB
        type: SINGLE
        shardKey: uid
        config:
          type: com.alibaba.druid.pool.DruidDataSource
          platform: mysql
          initialSize: 5
          minIdle: 5
          maxIdle: 5
          maxActive: 50
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall,log4j
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        connects:
          - url: jdbc:mysql://127.0.0.1:3306/user_db_00?useUnicode=true;characterEncoding=utf-8
            username: root
            password: root
            driverClassName: com.mysql.cj.jdbc.Driver
            dbName: userDb
            slaves:
              - url: jdbc:mysql://127.0.0.1:3306/user_db_01?useUnicode=true;characterEncoding=utf-8
                username: root
                password: root
                driverClassName: com.mysql.cj.jdbc.Driver
      USER_DB_CLUSTER:
        setDbName: USER_DB
        type: CLUSTER
        shardKey: uid
        config:
          type: com.alibaba.druid.pool.DruidDataSource
          platform: mysql
          initialSize: 5
          minIdle: 5
          maxIdle: 5
          maxActive: 50
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall,log4j
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          driver-class-name: com.mysql.cj.jdbc.Driver
        connects:
          - url: jdbc:mysql://127.0.0.1:3306/user_db_00?useUnicode=true;characterEncoding=utf-8
            username: root
            password: root
            driverClassName: com.mysql.cj.jdbc.Driver
            dbName: userDb00
            slaves:
              - url: jdbc:mysql://127.0.0.1:3306/user_db_01?useUnicode=true;characterEncoding=utf-8
                username: root
                password: root
                driverClassName: com.mysql.cj.jdbc.Driver
          - url: jdbc:mysql://127.0.0.1:3306/user_db_01?useUnicode=true;characterEncoding=utf-8
            username: root
            password: root
            driverClassName: com.mysql.cj.jdbc.Driver
            dbName: userDb01


