rubber:
  proxy:
    config:
      dbInstances: ## db实例的名称
        userDB: #数据库实例名称
          instanceName: userDB #数据库实例名称
          type: SINGLE  #数据库的类型，单例 或者或者集群 @see DBClusterType 两种模式都支持主从
          config: # 数据库的配置
            type: com.alibaba.druid.pool.DruidDataSource
            platform: mysql
            initialSize: 5
            minIdle: 5
            maxIdle: 5
            maxActive: 50
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
            filters: stat,wall,log4j
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          connects: #连接配置，支持多个master配置，当 type: SINGLE  的时候 读取第一个配置
            - url: jdbc:mysql://127.0.0.1:3306/user_db_00?useUnicode=true;characterEncoding=utf-8
              username: root
              password: root
              driverClassName: com.mysql.cj.jdbc.Driver
              dbName: userDb
              slaves: # 从库配置 所有的实例都可以设置多个从库配置
                - url: jdbc:mysql://127.0.0.1:3306/user_db_01?useUnicode=true;characterEncoding=utf-8
                  username: root
                  password: root
                  driverClassName: com.mysql.cj.jdbc.Driver
        USER_DB_CLUSTER: ## 实例2
          setDbName: USER_DB
          type: CLUSTER
          shardKey: uid
          config:
            type: com.alibaba.druid.pool.DruidDataSource
            platform: mysql
            initialSize: 5
            minIdle: 5
            maxIdle: 5
            maxActive: 50
            maxWait: 60000
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
            filters: stat,wall,log4j
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            driver-class-name: com.mysql.cj.jdbc.Driver
          connects: #连接配置，支持多个master配置，当 type: CLUSTER  的时候 ，支持多个配置
            - url: jdbc:mysql://127.0.0.1:3306/user_db_00?useUnicode=true;characterEncoding=utf-8
              username: root
              password: root
              driverClassName: com.mysql.cj.jdbc.Driver
              dbName: userDb00
              slaves:
                - url: jdbc:mysql://127.0.0.1:3306/user_db_01?useUnicode=true;characterEncoding=utf-8
                  username: root
                  password: root
                  driverClassName: com.mysql.cj.jdbc.Driver
            - url: jdbc:mysql://127.0.0.1:3306/user_db_01?useUnicode=true;characterEncoding=utf-8
              username: root
              password: root
              driverClassName: com.mysql.cj.jdbc.Driver
              dbName: userDb01
