rubber:
  redis:
    instance:
      normalRedis_Set:
        nodes:
          - 127.0.0.1:6379
        password: 123456
        maxAttempts: 100
        connectionTimeout: 8000
        soTimeout: 1000