rubber:
  sharding:
    dev:
      userDB:
        dbName: test_00_db
        type: com.alibaba.druid.pool.DruidDataSource
        platform: mysql
        initialSize: 5
        minIdle: 5
        maxIdle: 5
        maxActive: 50
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        master:
          url: jdbc:mysql://mysql.lottery.com:3306/lottery_system?useUnicode=true&amp;characterEncoding=utf-8
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
        slaves:
          slave1:
            url: jdbc:mysql://mysql.lottery.com:3306/lottery_system?useUnicode=true&amp;characterEncoding=utf-8
            username: root
            password: root
            driver-class-name: com.mysql.jdbc.Driver
          slave2:
            url: jdbc:mysql://mysql.lottery.com:3306/lottery_system?useUnicode=true&amp;characterEncoding=utf-8
            username: root
            password: root
            driver-class-name: com.mysql.jdbc.Driver

